on:
  push:
    branches: [main]

jobs:
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      # First check out the code from the github repo
      - name: checkout
        uses: actions/checkout@v1
      
      # Use the latest long term stable version of node
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install project dependencies
      - name: install
        run: yarn

      # Run linter
      - name: lint
        run: yarn lint

      # Run tests
      - name: tests
        run: yarn test
    
      # Build
      - name: build
        run: yarn build

      # Deploy
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
