on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      # First check out the code from the github repo
      - name: checkout
        uses: actions/checkout@v1
      
      # Use the latest long term stable version of node
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install project dependencies
      - name: install
        run: yarn

      # Run linter
      - name: lint
        run: yarn lint

      # Run tests
      - name: tests
        run: yarn test
    
      # Build
      - name: build
        run: yarn build